# Generated by Django 5.1.1 on 2024-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblPokemon',
            fields=[
                ('id_pokemon', models.AutoField(primary_key=True, serialize=False)),
                ('num_pokedex_pokemon', models.IntegerField()),
                ('name_pokemon', models.CharField(max_length=40)),
                ('img_pokemon', models.CharField(blank=True, max_length=255, null=True)),
                ('total_pokemon', models.IntegerField()),
                ('hp_pokemon', models.IntegerField()),
                ('atk_pokemon', models.IntegerField()),
                ('def_pokemon', models.IntegerField()),
                ('sp_atk_pokemon', models.IntegerField()),
                ('sp_def_pokemon', models.IntegerField()),
                ('speed_pokemon', models.IntegerField()),
                ('generation_pokemon', models.IntegerField()),
                ('legendary_pokemon', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_pokemon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTypes',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weaknesses_1', models.CharField(blank=True, max_length=20, null=True)),
                ('weaknesses_2', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_types',
                'managed': False,
            },
        ),
    ]
